// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_laleur_warior = "CgkIs7nV1LsMEAIQAA"; // <GPGSID>
        public const string achievement_laleur_captain = "CgkIs7nV1LsMEAIQAQ"; // <GPGSID>
        public const string achievement_the_god_of_laleur_dodge = "CgkIs7nV1LsMEAIQAw"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIs7nV1LsMEAIQBA"; // <GPGSID>
        public const string achievement_dodge_master_of_laleur = "CgkIs7nV1LsMEAIQAg"; // <GPGSID>

}

